# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      
      - name: Build shared module
        run: |
          gfortran-11 -O3 RMT_3D_UFG.f90 -IRMT_MacOS_x86_64 -c -o RMT_3D_UFG.o
          
      - name: Build and run program Parallel_Finest_Grid_Smoothing_M
        run: |
          cd Parallel_Finest_Grid_Smoothing_M
          gfortran-11 -O3 -fopenmp Parallel_Finest_Grid_Smoothing_1.f90 Parallel_Finest_Grid_Smoothing_2.f90 Parallel_Finest_Grid_Smoothing_M.f90 -o Parallel_Finest_Grid_Smoothing_M
          ./Parallel_Finest_Grid_Smoothing_M
          cat Parallel_Finest_Grid_Smoothing.03
          cd ..
          
      - name: Build and run program Integrals_M
        run: |
          cd Integrals_M
          gfortran-11 -O3 -fopenmp Integrals_1.f90 Integrals_2.f90 Integrals_M.f90 -I.. ../RMT_3D_UFG.o -I../RMT_MacOS_x86_64 -L../RMT_MacOS_x86_64 -lRMT_3D_2020_OpenMP -o Integrals_M
          ./Integrals_M
          for f in *.txt; do echo "$f"; head -n 10 "$f"; done
          cd ..
          
