# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      
      - name: Build shared module
        run: |
          gfortran-11 -O3 RMT_3D_UFG.f90 -IRMT_MacOS_x86_64 -c -o RMT_3D_UFG.o
          
      - name: Build and run program Parallel_Finest_Grid_Smoothing_M
        run: |
          cd Parallel_Finest_Grid_Smoothing_M
          gfortran-11 -O3 -fopenmp Parallel_Finest_Grid_Smoothing_1.f90 Parallel_Finest_Grid_Smoothing_2.f90 Parallel_Finest_Grid_Smoothing_M.f90 -o Parallel_Finest_Grid_Smoothing_M
          ./Parallel_Finest_Grid_Smoothing_M
          less Parallel_Finest_Grid_Smoothing.03
          cd ..
